### ISSUE TITLE
Question about the baby SSRF challenge

### ISSUE THREAD

**Issue by TheRubick** [Kaiziron/zh3r0_ctf_v2#1]
Hello Kariziron,
I enjoyed reading your writeup but I have a question, did you try to bypass the blacklist filters by submitting these payloads: 0177, 127.1, 0x7f000001, LoCaLHost and any of them worked with you?

**Comment by Kaiziron** [comment]
Yea, i have tried those too, using octal and hex notation such as 0177 and 0x7f000001 will work, decimal notation also works, however 127.1 and LoCaLHost would not, because its filtering "127" and "localhost" and I think it's case insensitive.

**Comment by TheRubick** [comment]
Okay got it thanks !!
